=== rasankhalidd/AiStudioProjectMgmt/xml-lab/customer_schema.xsd
<?xml>
<xs:schema>
  <xs:element name="Customers">
    <xs:complexType>

        <xs:element name="Customer" maxOccurs="unbounded">
          <xs:complexType>
              <xs:element name="ID" type="xs:string"/>
              <xs:element name="Name" type="xs:string"/>
              <xs:element name="Address">
                <xs:complexType>
                    <xs:element name="Street" type="xs:string"/>
                    <xs:element name="Zip" type="xs:string"/>                
                </xs:complexType>
              </xs:element>
              <xs:element name="DateOfBirth" type="xs:date"/>
              <xs:element name="TelephoneNumber">
                <xs:complexType>
                    <xs:element name="WorkNumber" type="xs:string"/>
                    <xs:element name="MobileNumber" type="xs:string"/>
                </xs:complexType>
              </xs:element>
          </xs:complexType>
        </xs:element>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rasankhalidd/AiStudioProjectMgmt/xml-lab/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<Customers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="customer_schema.xsd">

  <Customer>
    <ID>C001</ID>
    <Name>Rasan Khalid</Name>
    <Address>
      <Street>15 Kirkuk Road</Street>
      <Zip>36001</Zip>
    </Address>
    <DateOfBirth>2000-03-21</DateOfBirth>
    <TelephoneNumber>
      <WorkNumber>+964-62-123-4567</WorkNumber>
      <MobileNumber>+964-750-123-4567</MobileNumber>
    </TelephoneNumber>
  </Customer>

  <Customer>
    <ID>C002</ID>
    <Name>Las Abdalrahman</Name>
    <Address>
      <Street>7 Sulaymaniyah Street</Street>
      <Zip>46001</Zip>
    </Address>
    <DateOfBirth>1998-07-15</DateOfBirth>
    <TelephoneNumber>
      <WorkNumber>+964-53-234-5678</WorkNumber>
      <MobileNumber>+964-770-234-5678</MobileNumber>
    </TelephoneNumber>
  </Customer>

  <Customer>
    <ID>C003</ID>
    <Name>Saros Saman</Name>
    <Address>
      <Street>22 Erbil Avenue</Street>
      <Zip>44001</Zip>
    </Address>
    <DateOfBirth>2001-11-09</DateOfBirth>
    <TelephoneNumber>
      <WorkNumber>+964-66-345-6789</WorkNumber>
      <MobileNumber>+964-771-345-6789</MobileNumber>
    </TelephoneNumber>
  </Customer>

</Customers>
